cogs/call.py, cogs/fish.py, cogs/flow.py, cogs/help.py
－ 修改了 fish.py 現在不能在 Thread 裡產魚
－ 更改了某些指令回饋信息的格式（就是加空格，因為小雪打漏了）
－ 新增了我自己的 /call
－ 新增了 /rabbit [兔兔島萬歲]，同時在 /help 新增了 /rabbit 的說明
=> 小雪少打空格, 太可惡了

cogs/flow.py
Reverts seriaati/shenhe_bot#19
=> Revert "修改了三安幣的 Reaction"

UI_elements/genshin/EventTypeChooser.py, apps/text_map/maps/shenhe_text_map.yaml, cogs/genshin.py, utility/utils.py
- 新增了活動的開始時間跟結束時間
- 新增了活動的類別分頁
- 涵蓋了遊戲內的其他活動
- 把格式都換成了 discord 的 timestamp
=> 更好的 /events

UI_elements/genshin/ArtifactLeaderboard.py, cogs/genshin.py, text_maps/langs/en-US.yaml
- fixed artifact leaderbaord errors
- improved ranking logic
- shortened length of code
- added leaderboard position update error message
=> fix artifact leaderboard and improve code

apps/wish/wish_app.py, cogs/wish.py
- 400 was missed in 5 star and 4 star calculations
=> fixed limited banner issues

cogs/help.py, text_maps/langs/en-US.yaml
- subcommands will be displayed with group command name now (`/character` to `/calc character`)
- changed the descriptions of some categories
=> improved /help

apps/text_map/text_map_app.py, text_maps/langs/en-US.yaml
- fixed spelling mistakes in the English text map
- changed the behaviors of empty charcaters, `<EMPTY_CHARACTER>` will now be recognized as an empty character
=> Text map update

UI_elements/others/ChangeLang.py, cogs/others.py
- Updated Japanese translation progress
- Added crowdin link into `/lang`
=> /lang update

UI_elements/calc/AddToTodo.py, UI_elements/calc/CalcCharacter.py, UI_elements/calc/CalcWeapon.py, UI_elements/genshin/Abyss.py, UI_elements/genshin/AccountRegister.py, UI_elements/genshin/ArtifactLeaderboard.py, UI_elements/genshin/Build.py, UI_elements/genshin/CharacterWiki.py, UI_elements/genshin/Diary.py, UI_elements/genshin/EnkaDamageCalculator.py, UI_elements/genshin/EnkaProfile.py, UI_elements/genshin/TalentNotification.py, UI_elements/others/ChangeLang.py, UI_elements/others/ChangeLog.py, UI_elements/todo/TodoList.py, UI_elements/wish/ChoosePlatform.py, UI_elements/wish/ChooseWeapon.py, UI_elements/wish/SetAuthKey.py, cogs/waifu.py, config.py, debug.py, run.py, utility/paginator.py
- 新增 `short_timeout`, `mid_timeout`, `long_timeout`
- 移除所有 `timeout=None` （除了 persisten view)
- 移除大部分 persistent view
- view timeout 時會 disable UI elements
=> 修改 view 的 timeout

UI_elements/genshin/AccountRegister.py, UI_elements/genshin/ArtifactLeaderboard.py, UI_elements/genshin/Build.py, UI_elements/others/ChangeLog.py, UI_elements/todo/TodoList.py, cogs/calc.py, cogs/genshin.py, cogs/help.py, cogs/others.py, cogs/todo.py, cogs/waifu.py, cogs/wish.py, utility/paginator.py
- 有時候 view 會缺少 message 屬性，因此將 message 傳入來確保每次都能 disable UI element
=> 賦予 view message 屬性

UI_elements/genshin/AccountRegister.py, UI_elements/genshin/ArtifactLeaderboard.py, UI_elements/genshin/Build.py, UI_elements/others/ChangeLog.py, UI_elements/todo/TodoList.py, cogs/calc.py, cogs/genshin.py, cogs/help.py, cogs/others.py, cogs/todo.py, cogs/waifu.py, cogs/wish.py, utility/paginator.py
Reverts seriaati/shenhe_bot#152
=> Revert "賦予 view message 屬性"

UI_elements/calc/AddToTodo.py, cogs/calc.py
- use the todo cards in `/calc`
=> add calc cards

UI_elements/waifu/DeleteImage.py, UI_elements/waifu/HmtaiTag.py, UI_elements/waifu/WaifuImTag.py, apps/text_map/utils.py, apps/waifu/waifu_app.py, cogs/waifu.py
- Separate UI elements
- Separate waifu app
- Optimize images using PIL to reduce file size
- Add try except when file is too large
=> Improve /waifu

UI_elements/others/ManageAccounts.py, cogs/login.py
I updated `Hu Tao login gateway` python library to support resend token from HTTP request if websocket has doesn't recieved from Gateway
- I don't know how to replace original message function if user has click button reloaded
- I change from `.disconnect()` into `.close()` in `cogs.login`
Don't forgot update `Hu Tao login gateway` python library to use this code **ehe**
=> Update to support add user without if data has not received in gateway

UI_elements/genshin/Domain.py, ambr/models.py, apps/draw/draw_funcs/farm.py, apps/draw/main_funcs.py, apps/draw/utility.py, apps/genshin/custom_model.py, apps/genshin/utils.py, cogs/genshin.py, text_maps/langs/en-US.yaml, utility/paginator.py
Resolves https://github.com/seriaati/shenhe_bot/issues/569
=> New farm card

apps/genshin/enka.py, cogs/admin.py
Also adds a command to transfer data
=> feat: use yaml instead of pickle

apps/draw/utility.py
=> refactor: use f-strings

apps/genshin/enka.py, cogs/admin.py
Switching back to pickle since YAML is too slow.
Also uses a new library [srsly](https://github.com/explosion/srsly) in this update.
=> feat: use pickle instead of YAML

apps/db/custom_image.py, models.py, ui/others/settings/CustomImage.py
Disable `remove image` button when the image is provided by Shenhe
Sets `default=True` in select options if it is the current image
=> feat: improve custom image settings

cogs/help.py, models.py, ui/__init__.py, ui/help/__init__.py, ui/help/help.py
- Adds new model `EmbedField`
- Uses paginator to split up fields in `/help`
=> feat: improve help command

apps/db/json.py, apps/draw/draw_funcs/characters.py, apps/draw/main_funcs.py, apps/draw/utility.py, apps/genshin/genshin_app.py, apps/genshin/utility.py, asset.py, cogs/genshin.py, data/game/elements.py, models.py, run.py, text_maps/langs/en-US.yaml, ui/genshin/ShowAllCharacters.py
=> Character card revamp

apps/text_map/text_map_app.py, dev/enum.py
Reverts seriaati/shenhe_bot#697
=> Revert "feat: hot reload for text maps"

apps/text_map/text_map_app.py
=> feat: implement text map hot reload

apps/db/tables.py, apps/genshin/auto_task/daily_checkin.py, cogs/topgg.py, dev/base_ui.py, run.py, ui/genshin/leaderboard_view.py, utils/general.py
=> [Bug Report] Filter issues with leaderboard

ui/genshin/me_too.py
=> fix: send followups instead of editing message

apps/enka/models.py
=> fix: various bugs found on sentry

apps/db/tables/hoyo_account.py, apps/genshin/auto_task/daily_checkin.py
=> fix: ValidationError: 2 validation errors for HoyoAccount
